const CURRENT_USER_SET = 'CURRENT_USER_SET';
const CURRENT_USER_REMOVE = 'CURRENT_USER_REMOVE';
const CURRENT_USER_UPDATE = 'CURRENT_USER_UPDATE';

export default {
    CURRENT_USER_SET,
    CURRENT_USER_REMOVE,
    CURRENT_USER_UPDATE
}